export const Type={
    ADD_TO_BASKET:'ADD_TO_BASKET',
    REMOVE_FROM_BASKET:"REMOVE_FROM_BASKET"
}

// OR WE CAN USE THE BELLOW FORMAT IF WE ARE USING SAME NAME FOR RHE KEY VALUE PAIR 

// export const Type={
//     ADD_TO_BASKET,
//     REMOVE_FROM_BASKET
// }